name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.1.20452.10'
    - name: install-tools
      run: |
        dotnet tool install --global Arbor.Tooler.GlobalTool
        dotnet tool install --global Arbor.Build.Bootstrapper
    - name: EnableMultipleSdks
      shell: pwsh
      run: |
        $version = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Leaf;
        $root = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Parent;
        $directories = Get-ChildItem $root | Where-Object { $_.Name -ne $version };
        foreach ($dir in $directories) {
          $from = $dir.FullName;
          $to = "$root/$version";
          Write-Host Copying from $from to $to;
          Copy-Item "$from\*" $to -Recurse -Force;
        }
    - name: build
      env:
        Arbor.Build.NuGet.PackageUpload.Server.ApiKey: ${{ secrets.myget }}
        Arbor.Build.NuGet.PackageUpload.Server.Uri: "https://www.myget.org/F/arbor/api/v2/package"
        Arbor.Build.NuGet.PackageUpload.Enabled: "true"
        Arbor.Build.NuGet.PackageUpload.ForceUploadEnabled: "true"
      run: build\build.bat
